# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('label_id', models.TextField()),
            ],
            options={
                'verbose_name': 'Facebook label',
                'verbose_name_plural': 'Facebook labels',
            },
        ),
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('original_id', models.TextField()),
            ],
            options={
                'verbose_name': 'Facebook page',
                'verbose_name_plural': 'Facebook pages',
            },
        ),
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.TextField()),
            ],
            options={
                'verbose_name': 'Facebook user',
                'verbose_name_plural': 'Facebook users',
            },
        ),
        migrations.CreateModel(
            name='FacebookUserLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_api.FacebookLabel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_api.FacebookUser')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_api.FacebookPage')),
            ],
            options={
                'verbose_name': 'Facebook user label',
                'verbose_name_plural': 'Facebook user labels',
            },
        ),
    ]
